apiVersion: v1
kind: Service
metadata:
  name: local-host
  namespace: gremlin
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: local-host
  namespace: gremlin
subsets:
  - addresses:
      - ip: 192.168.64.1
    ports:
      - port: 8080
